### ISSUE TITLE
Consolidate GitHub orgs

### ISSUE THREAD

**Issue by timoguin** [tiki/roadmap#2]
Consolidate the [tiki](https://github.com/tiki) and [tiki-bar](https://github.com/tiki-bar) GitHub orgs.

## Tasks

- [x] https://github.com/tiki-bar/tiki-ocean-catalog/issues/3
- [x] https://github.com/tiki-bar/tiki-ocean-metadata/issues/2
- [x] https://github.com/tiki-bar/tiki-capture-receipt-capacitor/issues/133
- [x] https://github.com/tiki-bar/spring-rest-api/issues/24
- [x] https://github.com/tiki-bar/tiki-sdk-capacitor/issues/47
- [x] https://github.com/tiki-bar/worker-utils-ts/issues/38
- [x] https://github.com/tiki-bar/tiki-receipt-capacitor/issues/114
- [x] https://github.com/tiki-bar/tiki-ocean/issues/9
- [x] https://github.com/tiki-bar/tiki-ocean-data/issues/2
- [x] https://github.com/tiki-bar/l0-auth-plugin/issues/55
- [x] https://github.com/tiki-bar/.github/issues/1
- [x] https://github.com/tiki-bar/dart-from-native/issues/1
- [x] https://github.com/tiki-bar/l0-index-plugin/issues/72
- [x] https://github.com/tiki-bar/pool-kgraph/issues/37
- [x] https://github.com/tiki-bar/dart-httpp/issues/10
- [x] https://github.com/tiki-bar/flutter-kv/issues/13
- [x] https://github.com/tiki-bar/flutter-zendesk/issues/46
- [x] https://github.com/tiki-bar/flutter-upvoty/issues/40
